 
server:
  port: 8081
management:
  health:
    circuitbreakers:
      enabled: true
   
  endpoints:
    web:
      exposure:
        include: health
        
  endpoint:
    health:
      show-details: always
             
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermicroservices
    username: root
    password: Acchu@2000
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:  
        dialect: org.hibernate.dialect.MySQL8Dialect


  application:
    name: USER-SERVICE
   

           
  config:
    import: optional:configserver:http://localhost:8085

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50 
        minimumNumberOfCalls: 5 
        automaticTransitionFromOpenToHalfOpenState: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
          
  
  
  